"""Add analysis fields to SearchResult

Revision ID: ec354de19d8d
Revises: 0338e0db7107
Create Date: 2024-11-01 15:58:34.286995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec354de19d8d'
down_revision = '0338e0db7107'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('search_result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('analysis', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('company_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('potential_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('sales_notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('company_description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('annual_revenue', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('country', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('website', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('assumed_website', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('search_result', schema=None) as batch_op:
        batch_op.drop_column('assumed_website')
        batch_op.drop_column('website')
        batch_op.drop_column('country')
        batch_op.drop_column('annual_revenue')
        batch_op.drop_column('company_description')
        batch_op.drop_column('sales_notes')
        batch_op.drop_column('potential_score')
        batch_op.drop_column('company_name')
        batch_op.drop_column('analysis')

    # ### end Alembic commands ###
